[package]
name = "handletest"
version = "0.1.0"
authors = ["christian <christian@chfi.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlegraph = "0.6"
gfa = "0.9"
fnv = "1.0"
anyhow = "1.0"
bstr = "0.2"
